id: P005404
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:48:37.954658
source_metadata:
  id: bdr:W8LS19234
  title: སྨན་སྦྱོར་ལག་ལེན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    a6505465449e4c0b91120f98900ab413:
      image_group_id: I8LS19236
      title: ''
      volume_number: 1
      total_pages: 716
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
